-- Run this once in Supabase Dashboard > SQL Editor > New query.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (char_length(username) between 3 and 24),
  created_at timestamptz not null default now()
);

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  name text not null,
  category text not null check (category in ('PC/Laptops','Keyboards','Mouses','Mics','Headsets')),
  price numeric not null check (price > 0),
  condition text not null check (condition in ('Like new','Good','Fair')),
  status text not null default 'Available' check (status in ('Available','Reserved','Sold')),
  image text not null,
  description text not null,
  specs jsonb not null default '{}'::jsonb,
  missing text[] not null default '{}',
  seller text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.listings enable row level security;
create policy "Profiles visible to everyone" on public.profiles for select using (true);
create policy "Users create own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Owners update profile" on public.profiles for update using (auth.uid() = id);
create policy "Listings visible to everyone" on public.listings for select using (true);
create policy "Signed-in users create listings" on public.listings for insert to authenticated with check (auth.uid() = owner_id);
create policy "Owners update listings" on public.listings for update using (auth.uid() = owner_id);
create policy "Owners delete listings" on public.listings for delete using (auth.uid() = owner_id);
