export type Category = "PC/Laptops" | "Keyboards" | "Mouses" | "Mics" | "Headsets";
export type Listing = { id: number; name: string; category: Category; price: number; condition: "Like new" | "Good" | "Fair"; status: "Available" | "Reserved" | "Sold"; image: string; description: string; specs: Record<string, string>; missing: string[]; seller: string; posted: string; };
export const categories: { name: Category; icon: string; hint: string }[] = [
  { name: "PC/Laptops", icon: "▣", hint: "GPU, CPU, RAM, storage" }, { name: "Keyboards", icon: "⌨", hint: "switches, layout, size" }, { name: "Mouses", icon: "◉", hint: "weight, sensor, wireless" }, { name: "Mics", icon: "◌", hint: "USB/XLR, pickup pattern" }, { name: "Headsets", icon: "◖", hint: "wired, wireless, platform" }
];
const photo = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;
// Specs are local mock marketplace data. Images are product/category photography for prototype presentation.
export const starterListings: Listing[] = [
  { id: 1, name: "Logitech G Pro X Superlight", category: "Mouses", price: 78, condition: "Good", status: "Available", image: photo("photo-1527814050087-3793815479db"), description: "Tournament-ready lightweight wireless mouse. Receiver and cable included.", specs: { Weight: "63 g", Connection: "Wireless", Sensor: "HERO 25K", Color: "White" }, missing: [], seller: "Kai", posted: "2 hours ago" },
  { id: 2, name: "Razer Huntsman Mini", category: "Keyboards", price: 62, condition: "Like new", status: "Available", image: "https://cdn.iset.io/assets/00665/produtos/3803/teclado-razer-huntsman-mini-black-opto-mechanical-switch-purple-01.png", description: "Compact 60% optical keyboard with original box and detachable cable.", specs: { Layout: "60%", Switches: "Linear optical", Connection: "Wired", Lighting: "RGB" }, missing: [], seller: "Mina", posted: "5 hours ago" },
  { id: 3, name: "HyperX Cloud II Wireless", category: "Headsets", price: 55, condition: "Good", status: "Available", image: photo("photo-1599669454699-248893623440"), description: "Comfortable wireless headset for PC and PlayStation. Fresh ear pads included.", specs: { Connection: "Wireless", Battery: "Up to 30 hours", Platform: "PC, PlayStation", Microphone: "Detachable" }, missing: ["Exact battery health"], seller: "Rey", posted: "Yesterday" },
  { id: 4, name: "Blue Yeti USB Microphone", category: "Mics", price: 70, condition: "Good", status: "Reserved", image: photo("photo-1590602847861-f357a9332bbc"), description: "USB desktop microphone with multiple pickup patterns and a sturdy stand.", specs: { Connection: "USB", Pattern: "Cardioid, omni, stereo", Monitoring: "3.5 mm", Stand: "Included" }, missing: ["Whether a USB cable is included"], seller: "Jules", posted: "Yesterday" },
  { id: 5, name: "ASUS ROG Zephyrus G14", category: "PC/Laptops", price: 740, condition: "Good", status: "Available", image: "https://files.pccasegear.com/images/GA403UU-QS079W-thumb.jpg", description: "Portable gaming laptop with charger. Clean Windows installation.", specs: { CPU: "Ryzen 9 5900HS", GPU: "RTX 3060", RAM: "16 GB", Storage: "1 TB SSD" }, missing: ["Battery health", "Screen refresh rate"], seller: "Noah", posted: "2 days ago" },
  { id: 6, name: "SteelSeries Arctis 7", category: "Headsets", price: 42, condition: "Fair", status: "Available", image: photo("photo-1546435770-a3e426bf472b"), description: "Wireless headset with clear retractable mic. Cosmetic headband wear.", specs: { Connection: "Wireless", Platform: "PC, PlayStation", Microphone: "Retractable", Color: "Black" }, missing: ["Battery health", "Original receiver included"], seller: "Ari", posted: "3 days ago" },
  { id: 7, name: "Keychron K2", category: "Keyboards", price: 49, condition: "Good", status: "Available", image: photo("photo-1587829741301-dc798b83add3"), description: "Hot-swappable 75% mechanical keyboard for work and gaming.", specs: { Layout: "75%", Switches: "Gateron Brown", Connection: "Bluetooth / wired", Lighting: "White backlight" }, missing: [], seller: "Sam", posted: "3 days ago" },
  { id: 8, name: "Razer Viper Mini", category: "Mouses", price: 22, condition: "Good", status: "Sold", image: photo("photo-1615663245857-ac93bb7c39e7"), description: "Small wired gaming mouse in excellent working condition.", specs: { Weight: "61 g", Connection: "Wired", Sensor: "8500 DPI", Color: "Black" }, missing: ["Original packaging"], seller: "Chen", posted: "4 days ago" },
  { id: 9, name: "Elgato Wave 3", category: "Mics", price: 96, condition: "Like new", status: "Available", image: photo("photo-1593697821252-0c9137d9fc45"), description: "USB microphone with clipguard and Wave Link support.", specs: { Connection: "USB-C", Pattern: "Cardioid", Monitoring: "3.5 mm", Stand: "Included" }, missing: [], seller: "Tara", posted: "5 days ago" },
  { id: 10, name: "Custom RTX 3070 Gaming PC", category: "PC/Laptops", price: 880, condition: "Like new", status: "Available", image: photo("photo-1587202372775-e229f172b9d7"), description: "Ready-to-play desktop with a clean cable build. Collection only.", specs: { CPU: "Ryzen 5 5600X", GPU: "RTX 3070", RAM: "32 GB", Storage: "1 TB NVMe" }, missing: ["Power-supply model", "Benchmark results"], seller: "Dev", posted: "1 week ago" },
  { id: 11, name: "Sony INZONE H5", category: "Headsets", price: 68, condition: "Like new", status: "Available", image: photo("photo-1505740420928-5e560c06d30e"), description: "Lightweight wireless gaming headset with 2.4 GHz dongle.", specs: { Connection: "Wireless", Battery: "28 hours rated", Platform: "PC, PlayStation", Microphone: "Boom" }, missing: [], seller: "Elle", posted: "1 week ago" },
  { id: 12, name: "Fifine K688 Dynamic Mic", category: "Mics", price: 45, condition: "Good", status: "Available", image: photo("photo-1516280440614-37939bbacd81"), description: "Dynamic USB/XLR microphone, shock mount included.", specs: { Connection: "USB-C / XLR", Pattern: "Cardioid", Monitoring: "3.5 mm", Stand: "Not included" }, missing: ["USB cable included"], seller: "Ish", posted: "1 week ago" }
];
