import { useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { categories, listings, type Category, type Listing } from "./data";
import "./styles.css";
import "./comparison.css";
import "./nyx-qa.css";

const keywords: Record<string, string[]> = {
  budget: ["cheap", "budget", "affordable", "under", "low"], wireless: ["wireless", "bluetooth"], light: ["light", "lightweight"], competitive: ["competitive", "esports", "fps"], compact: ["compact", "small", "60%", "75%"], laptop: ["laptop", "portable"], streaming: ["stream", "streaming", "voice"], pc: ["pc", "desktop"], playstation: ["playstation", "ps5", "ps4"]
};

function matchesNeed(item: Listing, query: string) {
  const text = `${item.name} ${item.description} ${Object.values(item.specs).join(" ")}`.toLowerCase();
  const q = query.toLowerCase(); let score = item.status === "Available" ? 2 : -4;
  if (q && text.includes(q)) score += 5;
  Object.entries(keywords).forEach(([need, words]) => { if (words.some(w => q.includes(w)) && (text.includes(need) || words.some(w => text.includes(w)))) score += 3; });
  const budget = q.match(/(?:under|below|less than|\$)\s*\$?(\d+)/); if (budget) score += item.price <= Number(budget[1]) ? 4 : -3;
  if (q.includes("competitive") && item.category === "Mouses" && item.price > 40) score += 2;
  return score;
}

function App() {
  const [category, setCategory] = useState<Category | "All">("All");
  const [search, setSearch] = useState(""); const [need, setNeed] = useState("");
  const [selected, setSelected] = useState<Listing | null>(null); const [compare, setCompare] = useState<Listing[]>([]); const [showCompare, setShowCompare] = useState(false); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState("");
  const visible = useMemo(() => listings.filter(x => (category === "All" || x.category === category) && `${x.name} ${x.description}`.toLowerCase().includes(search.toLowerCase())), [category, search]);
  const recommendations = useMemo(() => listings.filter(x => category === "All" || x.category === category).map(item => ({ item, score: matchesNeed(item, need) })).sort((a,b) => b.score-a.score), [category, need]);
  const exact = recommendations.filter(x => x.score >= 5).slice(0, 3); const alternatives = recommendations.filter(x => !exact.some(e => e.item.id === x.item.id)).slice(0, 2);
  const toggleCompare = (item: Listing) => setCompare(old => old.some(x => x.id === item.id) ? old.filter(x => x.id !== item.id) : old.length < 2 ? [...old, item] : [old[1], item]);
  const why = (item: Listing) => { const parts = [item.status === "Available" ? "available now" : item.status.toLowerCase(), `${item.condition.toLowerCase()} condition`]; if (need.match(/under|below|\$/i)) parts.push(`priced at $${item.price}`); const relevant = Object.entries(item.specs).find(([,v]) => need && v.toLowerCase().includes(need.toLowerCase())); if (relevant) parts.push(`${relevant[0].toLowerCase()}: ${relevant[1]}`); return `Recommended because it is ${parts.join(", ")}.`; };
  return <main>
    <nav><a className="brand" href="#top">GEAR<span>DROP</span></a><div className="nav-links"><a href="#browse">Browse</a><a href="#nyx">Ask Nyx</a><button className="sell">+ Sell gear</button></div></nav>
    <section className="hero" id="top"><p className="eyebrow">SECOND-HAND. FIRST-CLASS.</p><h1>Your next <i>loadout</i><br/>is already here.</h1><p className="lede">Buy and sell pre-loved gaming gear with people who know their tech.</p><a className="cta" href="#browse">Explore the drop ↓</a><div className="hero-art"><span>⌨</span><span>◉</span><span>◖</span></div></section>
    <section className="category-section"><div><p className="eyebrow">SHOP BY SETUP</p><h2>What are you hunting for?</h2></div><div className="categories">{categories.map(c => <button className={category === c.name ? "category active" : "category"} onClick={() => { setCategory(c.name); document.getElementById("browse")?.scrollIntoView({behavior:"smooth"}); }} key={c.name}><b>{c.icon}</b><span>{c.name}</span><small>{c.hint}</small></button>)}</div></section>
    <section className="nyx" id="nyx"><div className="nyx-copy"><p className="eyebrow">MEET NYX ✦</p><h2>Not sure what gear<br/>fits your game?</h2><p>Tell Nyx what you need in your own words. It reads the listings, finds the best fit, and tells you exactly why.</p></div><div className="nyx-panel"><div className="orb">✦</div><h3>What are you looking for?</h3><p className="muted">{category === "All" ? "Choose a category or describe any gaming gear." : `Looking in ${category}.`}</p><textarea value={need} onChange={e => setNeed(e.target.value)} placeholder="e.g. A lightweight wireless mouse under $80 for competitive FPS..." /><div className="prompt-row"><button onClick={() => setNeed("lightweight wireless mouse under $80 for competitive FPS")}>Try an example</button><button className="ask" onClick={() => document.getElementById("recommendations")?.scrollIntoView({behavior:"smooth"})}>Ask Nyx →</button></div></div></section>
    {need && <section className="recommendations" id="recommendations"><p className="eyebrow">NYX'S PICKS</p><h2>Best matches for you</h2><p className="muted">Based on: “{need}”</p><div className="recommendation-grid">{exact.length ? exact.map(({item}) => <Recommendation item={item} why={why(item)} onOpen={setSelected} />) : <p className="empty">No exact match found. Here are the closest available alternatives.</p>}</div><h3>Also worth a look</h3><div className="recommendation-grid">{alternatives.map(({item}) => <Recommendation item={item} why={why(item)} onOpen={setSelected} />)}</div></section>}
    <section className="browse" id="browse"><div className="section-title"><div><p className="eyebrow">FRESH DROPS</p><h2>Browse the marketplace</h2></div><input aria-label="Search listings" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search gear..." /></div><div className="filters"><button className={category === "All" ? "active" : ""} onClick={() => setCategory("All")}>All gear</button>{categories.map(c => <button className={category === c.name ? "active" : ""} onClick={() => setCategory(c.name)} key={c.name}>{c.name}</button>)}</div><div className="listing-grid">{visible.map(item => <Card key={item.id} item={item} onOpen={setSelected} />)}</div>{!visible.length && <p className="empty">No listings match that search. Try a different category or phrase.</p>}</section>
    {compare.length > 0 && <aside className="compare-bar"><span>{compare.length}/2 selected to compare</span><div>{compare.map(x => <small key={x.id}>{x.name}</small>)}<button onClick={() => compare.length === 2 && setShowCompare(true)} disabled={compare.length !== 2}>Compare →</button></div></aside>}
    {showCompare && compare.length === 2 && <div className="overlay" role="dialog" aria-modal="true"><article className="comparison"><button className="close" onClick={() => setShowCompare(false)}>×</button><p className="eyebrow">NYX COMPARISON</p><h2>Which one suits you better?</h2><p className="muted">Nyx keeps your current request in mind: {need || "no requirements entered yet"}.</p><div className="compare-grid"><div className="compare-labels"><b>Price</b><b>Condition</b><b>Availability</b><b>Specifications</b><b>Listing confidence</b></div>{compare.map(item => <div className="compare-item" key={item.id}><span>{item.image}</span><h3>{item.name}</h3><strong>${item.price}</strong><p>{item.condition}</p><p>{item.status}</p><div>{Object.entries(item.specs).map(([k,v]) => <small key={k}><b>{k}:</b> {v}</small>)}</div><p className={item.missing.length ? "warning" : "complete"}>{item.missing.length ? `Missing: ${item.missing.join(", ")}` : "All key details provided"}</p></div>)}</div><p className="nyx-verdict"><b>Nyx's take:</b> {compare[0].status === "Available" && compare[0].price <= compare[1].price ? `${compare[0].name} is the stronger value for your current needs.` : `${compare[1].name} is the stronger value for your current needs.`}</p></article></div>}
    {selected && <div className="overlay" role="dialog" aria-modal="true"><article className="detail"><button className="close" onClick={() => setSelected(null)}>×</button><div className="detail-symbol">{selected.image}</div><div><p className="eyebrow">{selected.category} · {selected.status}</p><h2>{selected.name}</h2><p className="price">${selected.price}</p><p>{selected.description}</p><div className="specs">{Object.entries(selected.specs).map(([k,v]) => <div key={k}><small>{k}</small><b>{v}</b></div>)}</div>{selected.missing.length > 0 && <div className="missing"><b>Nyx noticed missing information</b><p>This listing does not confirm: {selected.missing.join(", ")}.</p></div>}<div className="ask-product"><b>Ask Nyx about this listing</b><div><input value={question} onChange={e => setQuestion(e.target.value)} placeholder="e.g. Is this good for competitive gaming?"/><button onClick={() => setAnswer(question ? (selected.missing.length ? `Based on the listing, ${selected.name} looks suitable, but ask the seller to confirm ${selected.missing.join(" and ")} before deciding.` : `Based on its listed specs, ${selected.name} looks like a solid fit. Its ${Object.entries(selected.specs).slice(0,2).map(([k,v]) => `${k.toLowerCase()} of ${v}`).join(" and ")} are the strongest signals.`) : "Ask a question and Nyx will use the listing details to guide you.")}>Ask</button></div>{answer && <p className="nyx-answer">✦ {answer}</p>}</div><div className="detail-actions"><button className="cta" onClick={() => alert("Prototype only: message flow is not connected.")}>Message {selected.seller}</button><button onClick={() => toggleCompare(selected)}> {compare.some(x => x.id === selected.id) ? "Remove from comparison" : "Compare this item"}</button></div></div></article></div>}
  </main>
}
function Card({ item, onOpen }: {item: Listing; onOpen: (x: Listing) => void}) { return <article className="card" onClick={() => onOpen(item)}><div className="product-art">{item.image}<span className={item.status.toLowerCase()}>{item.status}</span></div><div className="card-body"><small>{item.category}</small><h3>{item.name}</h3><p>${item.price} <span>· {item.condition}</span></p><small>Listed {item.posted}</small></div></article>; }
function Recommendation({ item, why, onOpen }: {item: Listing; why: string; onOpen: (x: Listing) => void}) { return <article className="rec"><div className="rec-top"><span>{item.image}</span><div><h3>{item.name}</h3><b>${item.price}</b></div><button onClick={() => onOpen(item)}>View</button></div><p><b>Why Nyx picked it:</b> {why}</p>{item.missing.length > 0 && <small className="warning">Missing: {item.missing.join(", ")}</small>}</article>; }

createRoot(document.getElementById("root")!).render(<App />);
