import { useEffect, useMemo, useState, type FormEvent } from "react";
import { createRoot } from "react-dom/client";
import { categories, starterListings, type Category, type Listing } from "./data";
import { deleteListing, getSession, loadListings, saveListing, signIn, signOut, signUp, type Session } from "./supabase";
import "./styles.css";
import "./theme.css";
import "./compare.css";
import "./safety.css";
import "./delete.css";

const photos: Record<Category,string> = {
  "PC/Laptops":"https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=900&q=80",
  Keyboards:"https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
  Mouses:"https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80",
  Mics:"https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=80",
  Headsets:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80"
};
function App() {
  const [items,setItems]=useState(starterListings); const [category,setCategory]=useState<Category|"All">("All");
  const [search,setSearch]=useState(""); const [need,setNeed]=useState(""); const [ask,setAsk]=useState(""); const [answer,setAnswer]=useState("");
  const [selected,setSelected]=useState<Listing|null>(null); const [selling,setSelling]=useState(false); const [toast,setToast]=useState(""); const [session,setSession]=useState<Session|null>(getSession()); const [auth,setAuth]=useState(false); const [compare,setCompare]=useState<Listing[]>([]); const [compareQuestion,setCompareQuestion]=useState(""); const [compareAnswer,setCompareAnswer]=useState(""); const [deleteCandidate,setDeleteCandidate]=useState<Listing|null>(null);
  const [theme,setTheme]=useState<"light"|"dark">(() => window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
  const [page,setPage]=useState(()=>window.location.hash.startsWith("#privacy-safety")?"safety":"market");
  useEffect(()=>{document.documentElement.dataset.theme=theme;},[theme]);
  useEffect(()=>{const update=()=>setPage(window.location.hash.startsWith("#privacy-safety")?"safety":"market");window.addEventListener("hashchange",update);return()=>window.removeEventListener("hashchange",update);},[]);
  useEffect(()=>{loadListings().then(remote=>{if(remote.length)setItems([...remote.map(item=>({...item,id:item.id+1000000})),...starterListings]);});},[]);
  const shown=useMemo(()=>items.filter(x=>(category==="All"||x.category===category)&&(x.name+" "+x.description).toLowerCase().includes(search.toLowerCase())),[items,category,search]);
  const picks=useMemo(()=>items.filter(x=>x.status==="Available").sort((a,b)=>rank(b,need)-rank(a,need)).slice(0,3),[items,need]);
  function generalAnswer(){const best=picks[0];setAnswer(best?"Nyx suggests starting with "+best.name+". It is available for $"+best.price+" and is listed as "+best.condition.toLowerCase()+" condition.":"Ask Nyx about a category or your budget.");}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session){setSelling(false);setAuth(true);return;}const f=new FormData(e.currentTarget);const cat=String(f.get("category")) as Category;const details=String(f.get("details"));const listing={name:String(f.get("name")),category:cat,price:Number(f.get("price")),condition:String(f.get("condition")) as Listing["condition"],status:"Available" as const,image:photos[cat],description:String(f.get("description")),specs:{Details:details||"Seller has not added specifications."},missing:details?[]:["Key specifications"],seller:String(f.get("seller"))||"You"};if(!details&&!window.confirm("Are you sure you want to proceed? You are missing key specifications that buyers may be looking for."))return;try{const saved=await saveListing(listing,session);setItems(old=>[{...saved,id:saved.id+1000000},...old]);setSelling(false);setToast("Your product is now listed. Good luck!");}catch(error){setToast(error instanceof Error?error.message:"Could not save listing.");}setTimeout(()=>setToast(""),4000);}
  const navigation=<nav><a className="brand" href="#top">GEAR<span>DROP</span></a><div><a href="#browse">Browse</a><a href="#nyx">Ask Nyx</a><a href="#privacy-safety-questions">Privacy &amp; Safety</a><button className="theme-toggle" onClick={()=>setTheme(theme==="light"?"dark":"light")} aria-label="Toggle colour theme">{theme==="light"?"☾":"☀"}</button>{session?<button className="login" onClick={async()=>{await signOut(session);setSession(null);setToast("You have been logged out.");}}>Log out</button>:<button className="login" onClick={()=>setAuth(true)}>Sign in</button>}<button className="sell" onClick={()=>session?setSelling(true):setAuth(true)}>+ Sell gear</button></div></nav>;
  if(page==="safety")return <main>{navigation}<SafetyPage/></main>;
  return <main>
    {navigation}
    <section className="hero" id="top"><div><p className="eyebrow">SECOND-HAND. FIRST-CLASS.</p><h1>Your next <i>loadout</i><br/>is already here.</h1><p>Pre-loved gaming gear, matched to the way you play.</p><a className="cta" href="#browse">Explore the drop ↓</a></div><div className="hero-gallery"><img src={starterListings[1].image} alt="Gaming keyboard"/><img src={starterListings[0].image} alt="Gaming mouse"/><img src={starterListings[4].image} alt="Gaming laptop"/></div></section>
    <section className="categories-section"><p className="eyebrow">SHOP BY SETUP</p><h2>What are you hunting for?</h2><div className="categories">{categories.map(c=><button className={category===c.name?"active":""} onClick={()=>{setCategory(c.name);document.querySelector("#browse")?.scrollIntoView({behavior:"smooth"});}} key={c.name}><b>{c.icon}</b><span>{c.name}</span><small>{c.hint}</small></button>)}</div></section>
    <section className="nyx" id="nyx"><div><p className="eyebrow">MEET NYX ✦</p><h2>Ask about a setup,<br/>not just a listing.</h2><p>Use Nyx for recommendations, broad gear advice, or questions about one product.</p><button className="nyx-wave" onClick={()=>setAnswer("Hi, I’m Nyx. Tell me what kind of gear you are looking for and I’ll help you narrow it down.")}>Say hi to Nyx ✦</button></div><div className="nyx-panel"><div className="nyx-mascot" aria-label="Animated Nyx assistant"><span className="antenna">✦</span><span className="eye left"></span><span className="eye right"></span><span className="glow"></span></div><label>Describe what you need</label><textarea value={need} onChange={e=>setNeed(e.target.value)} placeholder="A lightweight wireless mouse under $80 for FPS..."/><button className="example" onClick={()=>setNeed("lightweight wireless mouse under $80 for FPS")}>Try an example</button><label>Ask Nyx a general question</label><div className="question-row"><input value={ask} onChange={e=>setAsk(e.target.value)} placeholder="What should I check before buying a used laptop?"/><button onClick={generalAnswer}>Ask →</button></div>{answer&&<p className="nyx-answer">✦ {answer}</p>}</div></section>
    {need&&<section className="recommendations"><p className="eyebrow">NYX'S PICKS</p><h2>Best matches for you</h2><p className="muted">Based on: “{need}”. Change your words to refine results.</p><div className="recommendation-grid">{picks.map(item=><Recommendation item={item} onOpen={setSelected} key={item.id}/>)}</div></section>}
    <section className="browse" id="browse"><div className="section-title"><div><p className="eyebrow">FRESH DROPS</p><h2>Browse the marketplace</h2></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search gear..."/></div><div className="filters"><button className={category==="All"?"active":""} onClick={()=>setCategory("All")}>All gear</button>{categories.map(c=><button className={category===c.name?"active":""} onClick={()=>setCategory(c.name)} key={c.name}>{c.name}</button>)}</div><div className="listing-grid">{shown.map(item=><Card item={item} onOpen={setSelected} key={item.id}/>)}</div></section>
    <section className="compare-section"><p className="eyebrow">MODEL MATCHUP</p><h2>Want to compare models?</h2><p>Choose a listing, then click <b>Compare models</b> on that listing to select another model in the same category.</p>{compare.length===0&&<div className="compare-empty">No models selected yet.</div>}{compare.length===1&&<div className="compare-empty">{compare[0].name} selected. Open another {compare[0].category} listing and click Compare models.</div>}{compare.length===2&&<div className="compare-workspace"><div className="compare-table"><div className="compare-head"></div>{compare.map(item=><div className="compare-head" key={item.id}><img src={item.image} alt=""/><b>{item.name}</b><span>${item.price}</span></div>)}{["Condition","Availability","Specifications","Missing information"].map(label=><div className="compare-row" key={label}><b>{label}</b>{compare.map(item=><div key={item.id}>{label==="Condition"?item.condition:label==="Availability"?item.status:label==="Specifications"?Object.entries(item.specs).map(([k,v])=><small key={k}>{k}: {v}</small>):item.missing.length?item.missing.join(", "):"No key details missing"}</div>)}</div>)}</div><aside className="compare-nyx"><div className="mini-nyx">✦</div><h3>Ask Nyx about these models</h3><p>Nyx will use the selected models' listed details.</p><textarea value={compareQuestion} onChange={e=>setCompareQuestion(e.target.value)} placeholder="Which is better for FPS?"/><button onClick={()=>setCompareAnswer(compareQuestion?`${compare[0].name} is the better value if you prioritise ${compare[0].price<=compare[1].price?"price":"its listed specifications"}. Compare each model's condition and missing details before deciding.`:"Ask Nyx a question about the selected models.")}>Ask Nyx →</button>{compareAnswer&&<p className="nyx-answer">✦ {compareAnswer}</p>}<button className="clear-compare" onClick={()=>{setCompare([]);setCompareAnswer("");}}>Clear comparison</button></aside></div>}</section>
    {selected&&<Detail item={selected} close={()=>setSelected(null)} compare={compare} canDelete={Boolean(session&&selected.ownerId===session.user.id&&selected.databaseId)} requestDelete={()=>setDeleteCandidate(selected)} choose={(item)=>{setCompare(old=>old.length===0?[item]:old.some(x=>x.id===item.id)?old:old[0].category===item.category?[old[0],item]:[item]);setSelected(null);document.querySelector(".compare-section")?.scrollIntoView({behavior:"smooth"});}}/>} {deleteCandidate&&<DeleteConfirm cancel={()=>setDeleteCandidate(null)} confirm={async()=>{if(!session||!deleteCandidate.databaseId)return;try{await deleteListing(deleteCandidate.databaseId,session);setItems(old=>old.filter(item=>item.id!==deleteCandidate.id));setSelected(null);setDeleteCandidate(null);setToast("Listing is now removed.");}catch(error){setDeleteCandidate(null);setToast(error instanceof Error?error.message:"Could not remove listing.");}setTimeout(()=>setToast(""),4000);}}/>} {selling&&<Sell close={()=>setSelling(false)} submit={submit}/>} {auth&&<Auth close={()=>setAuth(false)} complete={setSession}/>} {toast&&<div className="toast">{toast}</div>}
  </main>;
}
function SafetyPage(){const questions=[["How do I pay safely?","Keep payment and messages on GearDrop until you can verify the item. Do not share bank details, passwords, or one-time codes. Meet in a safe public place for collection where possible."],["What should I check before buying?","Read the full description, compare specifications, and look for the missing-information notice. Ask the seller about condition, accessories, faults, and proof that the item works before paying."],["How can I list gear responsibly?","Use your own photos and give an honest condition description. Include important details such as model, specifications, faults, included accessories, and whether the item has been tested."],["What should I do if something feels suspicious?","Stop the conversation, do not send money or personal information, and leave the transaction. For this prototype, use the contact route supplied by your project team to report the listing."]];useEffect(()=>{if(window.location.hash==="#privacy-safety-questions")document.querySelector("#safety-questions")?.scrollIntoView();},[]);return <section className="safety-page"><div className="safety-hero"><p className="eyebrow">PRIVACY &amp; SAFETY</p><h1>Trade smart.<br/><i>Game</i> safely.</h1><p>Simple guidance for buying and selling pre-loved gaming gear on GearDrop.</p><a className="cta" href="#safety-questions">Go to Q&amp;A ↓</a></div><div className="safety-grid"><article><b>Keep chats protected</b><p>Never share passwords, one-time codes, or unnecessary personal information.</p></article><article><b>Check before you pay</b><p>Confirm condition, specifications, and what is included before committing.</p></article><article><b>Meet with care</b><p>For in-person collections, choose a public place and bring a trusted person if needed.</p></article></div><section className="safety-questions" id="safety-questions"><p className="eyebrow">Q&amp;A</p><h2>Questions, answered.</h2>{questions.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section><a className="back-market" href="#top">← Back to marketplace</a></section>}
function rank(item:Listing,need:string){const text=(item.name+" "+item.description+" "+Object.values(item.specs).join(" ")).toLowerCase();let points=item.status==="Available"?3:-4;need.toLowerCase().split(" ").forEach(word=>{if(word.length>2&&text.includes(word))points+=2;});const money=need.match(/(\d+)/);if(money)points+=item.price<=Number(money[1])?4:-3;return points;}
function Card({item,onOpen}:{item:Listing;onOpen:(item:Listing)=>void}){return <article className="card" onClick={()=>onOpen(item)}><div className="product-art"><img src={item.image} alt={item.name}/><span>{item.status}</span></div><div><small>{item.category}</small><h3>{item.name}</h3><p><b>$</b>{item.price} <em>· {item.condition}</em></p><small>Listed {item.posted}</small></div></article>;}
function Recommendation({item,onOpen}:{item:Listing;onOpen:(item:Listing)=>void}){return <article className="rec"><img src={item.image}/><div><h3>{item.name}</h3><b>$</b>{item.price}<p><strong>Why Nyx picked it:</strong> {item.status==="Available"?"Available now":"Closest match"}, {item.condition.toLowerCase()} condition.</p>{item.missing.length>0&&<small className="warning">Missing: {item.missing.join(", ")}</small>}<button onClick={()=>onOpen(item)}>View listing →</button></div></article>;}
function Detail({item,close,compare,choose,canDelete,requestDelete}:{item:Listing;close:()=>void;compare:Listing[];choose:(item:Listing)=>void;canDelete:boolean;requestDelete:()=>void}){const[q,setQ]=useState("");const[a,setA]=useState("");const wrongCategory=compare.length===1&&compare[0].category!==item.category;return <div className="overlay"><article className="detail"><button className="close" onClick={close}>×</button><img src={item.image} alt={item.name}/><div><p className="eyebrow">{item.category} · {item.status}</p><h2>{item.name}</h2><p className="price">$ {item.price}</p><p>{item.description}</p><div className="specs">{Object.entries(item.specs).map(([key,value])=><div key={key}><small>{key}</small><b>{value}</b></div>)}</div>{item.missing.length>0&&<div className="missing"><b>Nyx noticed missing information</b><p>Ask the seller about: {item.missing.join(", ")}.</p></div>}<div className="ask-product"><b>Ask Nyx about this listing</b><div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Is this good for competitive gaming?"/><button onClick={()=>setA(q?(item.missing.length?"It may suit your needs, but confirm "+item.missing.join(" and ")+" first.":"It is a well-documented second-hand listing; compare its listed specs with your needs."):"Type a question for Nyx.")}>Ask</button></div>{a&&<p className="nyx-answer">✦ {a}</p>}</div><button className="cta">Message {item.seller}</button><button className="compare-button" disabled={wrongCategory} onClick={()=>choose(item)}>{wrongCategory?`Choose another ${compare[0].category} model`:`Compare models${compare.length===1?" with selected model":""}`}</button>{canDelete&&<button className="delete-listing" onClick={requestDelete}>Delete listing</button>}</div></article></div>;}
function DeleteConfirm({cancel,confirm}:{cancel:()=>void;confirm:()=>void}){return <div className="overlay"><section className="delete-confirm" role="dialog" aria-modal="true" aria-label="Delete listing confirmation"><h2>Are you sure you want to delete your listing</h2><p>This cannot be undone.</p><div><button onClick={cancel}>No</button><button className="delete-yes" onClick={confirm}>Yes</button></div></section></div>}
function Sell({close,submit}:{close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="overlay"><form className="sell-form" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><p className="eyebrow">CREATE A LISTING</p><h2>Drop your gear</h2><p className="muted">It will persist after refresh.</p><label>Seller username<input name="seller" required placeholder="Your username"/></label><label>Product name<input name="name" required placeholder="e.g. Logitech G305"/></label><label>Category<select name="category">{categories.map(c=><option key={c.name}>{c.name}</option>)}</select></label><div className="form-row"><label>Price (USD)<input name="price" type="number" min="1" required/></label><label>Condition<select name="condition"><option>Like new</option><option>Good</option><option>Fair</option></select></label></div><label>Description<textarea name="description" required placeholder="Condition, accessories and buyer notes."/></label><label>Key specifications<input name="details" placeholder="Wireless, 63 g, original box..."/></label><button className="submit">Publish listing →</button></form></div>;}
function Auth({close,complete}:{close:()=>void;complete:(s:Session)=>void}){const[mode,setMode]=useState<"in"|"up">("in");const[message,setMessage]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const session=mode==="in"?await signIn(String(f.get("username")),String(f.get("password"))):await signUp(String(f.get("username")),String(f.get("password")));if(!session)throw new Error("Account created, Please try to login to your account.");complete(session);close();}catch(error){setMessage(error instanceof Error?error.message:"Sign-in failed.");}}return <div className="overlay"><form className="sell-form" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><p className="eyebrow">NYX ACCOUNT</p><h2>{mode==="in"?"Welcome back":"Create account"}</h2><p className="muted">Username and password only for this prototype.</p><label>Username<input name="username" minLength={3} required/></label><label>Password<input name="password" type="password" minLength={6} required/></label>{message&&<p className="warning">{message}</p>}<button className="submit">{mode==="in"?"Sign in":"Create account"}</button><button type="button" className="example" onClick={()=>setMode(mode==="in"?"up":"in")}>{mode==="in"?"Need an account? Sign up":"Already have an account? Sign in"}</button></form></div>;}
createRoot(document.getElementById("root")!).render(<App/>);
