import { useEffect, useMemo, useState, type FormEvent } from "react";
import { createRoot } from "react-dom/client";
import { categories, starterListings, type Category, type Listing } from "./data";
import { getSession, loadListings, saveListing, signIn, signUp, type Session } from "./supabase";
import "./styles.css";
import "./theme.css";

const photos: Record<Category,string> = {
  "PC/Laptops":"https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=900&q=80",
  Keyboards:"https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
  Mouses:"https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80",
  Mics:"https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=80",
  Headsets:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80"
};
function App() {
  const [items,setItems]=useState(starterListings); const [category,setCategory]=useState<Category|"All">("All");
  const [search,setSearch]=useState(""); const [need,setNeed]=useState(""); const [ask,setAsk]=useState(""); const [answer,setAnswer]=useState("");
  const [selected,setSelected]=useState<Listing|null>(null); const [selling,setSelling]=useState(false); const [toast,setToast]=useState(""); const [session,setSession]=useState<Session|null>(getSession()); const [auth,setAuth]=useState(false);
  const [theme,setTheme]=useState<"light"|"dark">(() => window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
  useEffect(()=>{document.documentElement.dataset.theme=theme;},[theme]);
  useEffect(()=>{loadListings().then(remote=>{if(remote.length)setItems(remote);});},[]);
  const shown=useMemo(()=>items.filter(x=>(category==="All"||x.category===category)&&(x.name+" "+x.description).toLowerCase().includes(search.toLowerCase())),[items,category,search]);
  const picks=useMemo(()=>items.filter(x=>x.status==="Available").sort((a,b)=>rank(b,need)-rank(a,need)).slice(0,3),[items,need]);
  function generalAnswer(){const best=picks[0];setAnswer(best?"Nyx suggests starting with "+best.name+". It is available for $"+best.price+" and is listed as "+best.condition.toLowerCase()+" condition.":"Ask Nyx about a category or your budget.");}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session){setSelling(false);setAuth(true);return;}const f=new FormData(e.currentTarget);const cat=String(f.get("category")) as Category;const details=String(f.get("details"));const listing={name:String(f.get("name")),category:cat,price:Number(f.get("price")),condition:String(f.get("condition")) as Listing["condition"],status:"Available" as const,image:photos[cat],description:String(f.get("description")),specs:{Details:details||"Seller has not added specifications."},missing:details?[]:["Key specifications"],seller:String(f.get("seller"))||"You"};if(!details&&!window.confirm("Are you sure you want to proceed? You are missing key specifications that buyers may be looking for."))return;try{const saved=await saveListing(listing,session);setItems(old=>[saved,...old]);setSelling(false);setToast("Your listing is live and saved to Supabase.");}catch(error){setToast(error instanceof Error?error.message:"Could not save listing.");}setTimeout(()=>setToast(""),4000);}
  return <main>
    <nav><a className="brand" href="#top">GEAR<span>DROP</span></a><div><a href="#browse">Browse</a><a href="#nyx">Ask Nyx</a><button className="theme-toggle" onClick={()=>setTheme(theme==="light"?"dark":"light")} aria-label="Toggle colour theme">{theme==="light"?"☾":"☀"}</button><button className="login" onClick={()=>setAuth(true)}>{session?"Signed in":"Sign in"}</button><button className="sell" onClick={()=>session?setSelling(true):setAuth(true)}>+ Sell gear</button></div></nav>
    <section className="hero" id="top"><div><p className="eyebrow">SECOND-HAND. FIRST-CLASS.</p><h1>Your next <i>loadout</i><br/>is already here.</h1><p>Pre-loved gaming gear, matched to the way you play.</p><a className="cta" href="#browse">Explore the drop ↓</a></div><div className="hero-gallery"><img src={items[1].image}/><img src={items[0].image}/><img src={items[4].image}/></div></section>
    <section className="categories-section"><p className="eyebrow">SHOP BY SETUP</p><h2>What are you hunting for?</h2><div className="categories">{categories.map(c=><button className={category===c.name?"active":""} onClick={()=>{setCategory(c.name);document.querySelector("#browse")?.scrollIntoView({behavior:"smooth"});}} key={c.name}><b>{c.icon}</b><span>{c.name}</span><small>{c.hint}</small></button>)}</div></section>
    <section className="nyx" id="nyx"><div><p className="eyebrow">MEET NYX ✦</p><h2>Ask about a setup,<br/>not just a listing.</h2><p>Use Nyx for recommendations, broad gear advice, or questions about one product.</p><button className="nyx-wave" onClick={()=>setAnswer("Hi, I’m Nyx. Tell me what kind of gear you are looking for and I’ll help you narrow it down.")}>Say hi to Nyx ✦</button></div><div className="nyx-panel"><div className="nyx-mascot" aria-label="Animated Nyx assistant"><span className="antenna">✦</span><span className="eye left"></span><span className="eye right"></span><span className="glow"></span></div><label>Describe what you need</label><textarea value={need} onChange={e=>setNeed(e.target.value)} placeholder="A lightweight wireless mouse under $80 for FPS..."/><button className="example" onClick={()=>setNeed("lightweight wireless mouse under $80 for FPS")}>Try an example</button><label>Ask Nyx a general question</label><div className="question-row"><input value={ask} onChange={e=>setAsk(e.target.value)} placeholder="What should I check before buying a used laptop?"/><button onClick={generalAnswer}>Ask →</button></div>{answer&&<p className="nyx-answer">✦ {answer}</p>}</div></section>
    {need&&<section className="recommendations"><p className="eyebrow">NYX'S PICKS</p><h2>Best matches for you</h2><p className="muted">Based on: “{need}”. Change your words to refine results.</p><div className="recommendation-grid">{picks.map(item=><Recommendation item={item} onOpen={setSelected} key={item.id}/>)}</div></section>}
    <section className="browse" id="browse"><div className="section-title"><div><p className="eyebrow">FRESH DROPS</p><h2>Browse the marketplace</h2></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search gear..."/></div><div className="filters"><button className={category==="All"?"active":""} onClick={()=>setCategory("All")}>All gear</button>{categories.map(c=><button className={category===c.name?"active":""} onClick={()=>setCategory(c.name)} key={c.name}>{c.name}</button>)}</div><div className="listing-grid">{shown.map(item=><Card item={item} onOpen={setSelected} key={item.id}/>)}</div></section>
    {selected&&<Detail item={selected} close={()=>setSelected(null)}/>} {selling&&<Sell close={()=>setSelling(false)} submit={submit}/>} {auth&&<Auth close={()=>setAuth(false)} complete={setSession}/>} {toast&&<div className="toast">{toast}</div>}
  </main>;
}
function rank(item:Listing,need:string){const text=(item.name+" "+item.description+" "+Object.values(item.specs).join(" ")).toLowerCase();let points=item.status==="Available"?3:-4;need.toLowerCase().split(" ").forEach(word=>{if(word.length>2&&text.includes(word))points+=2;});const money=need.match(/(\d+)/);if(money)points+=item.price<=Number(money[1])?4:-3;return points;}
function Card({item,onOpen}:{item:Listing;onOpen:(item:Listing)=>void}){return <article className="card" onClick={()=>onOpen(item)}><div className="product-art"><img src={item.image} alt={item.name}/><span>{item.status}</span></div><div><small>{item.category}</small><h3>{item.name}</h3><p><b>$</b>{item.price} <em>· {item.condition}</em></p><small>Listed {item.posted}</small></div></article>;}
function Recommendation({item,onOpen}:{item:Listing;onOpen:(item:Listing)=>void}){return <article className="rec"><img src={item.image}/><div><h3>{item.name}</h3><b>$</b>{item.price}<p><strong>Why Nyx picked it:</strong> {item.status==="Available"?"Available now":"Closest match"}, {item.condition.toLowerCase()} condition.</p>{item.missing.length>0&&<small className="warning">Missing: {item.missing.join(", ")}</small>}<button onClick={()=>onOpen(item)}>View listing →</button></div></article>;}
function Detail({item,close}:{item:Listing;close:()=>void}){const[q,setQ]=useState("");const[a,setA]=useState("");return <div className="overlay"><article className="detail"><button className="close" onClick={close}>×</button><img src={item.image} alt={item.name}/><div><p className="eyebrow">{item.category} · {item.status}</p><h2>{item.name}</h2><p className="price">$ {item.price}</p><p>{item.description}</p><div className="specs">{Object.entries(item.specs).map(([key,value])=><div key={key}><small>{key}</small><b>{value}</b></div>)}</div>{item.missing.length>0&&<div className="missing"><b>Nyx noticed missing information</b><p>Ask the seller about: {item.missing.join(", ")}.</p></div>}<div className="ask-product"><b>Ask Nyx about this listing</b><div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Is this good for competitive gaming?"/><button onClick={()=>setA(q?(item.missing.length?"It may suit your needs, but confirm "+item.missing.join(" and ")+" first.":"It is a well-documented second-hand listing; compare its listed specs with your needs."):"Type a question for Nyx.")}>Ask</button></div>{a&&<p className="nyx-answer">✦ {a}</p>}</div><button className="cta">Message {item.seller}</button></div></article></div>;}
function Sell({close,submit}:{close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="overlay"><form className="sell-form" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><p className="eyebrow">CREATE A LISTING</p><h2>Drop your gear</h2><p className="muted">It will persist after refresh.</p><label>Seller username<input name="seller" required placeholder="Your username"/></label><label>Product name<input name="name" required placeholder="e.g. Logitech G305"/></label><label>Category<select name="category">{categories.map(c=><option key={c.name}>{c.name}</option>)}</select></label><div className="form-row"><label>Price (USD)<input name="price" type="number" min="1" required/></label><label>Condition<select name="condition"><option>Like new</option><option>Good</option><option>Fair</option></select></label></div><label>Description<textarea name="description" required placeholder="Condition, accessories and buyer notes."/></label><label>Key specifications<input name="details" placeholder="Wireless, 63 g, original box..."/></label><button className="submit">Publish listing →</button></form></div>;}
function Auth({close,complete}:{close:()=>void;complete:(s:Session)=>void}){const[mode,setMode]=useState<"in"|"up">("in");const[message,setMessage]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const session=mode==="in"?await signIn(String(f.get("username")),String(f.get("password"))):await signUp(String(f.get("username")),String(f.get("password")));if(!session)throw new Error("Account created. Disable email confirmation in Supabase Auth settings, then sign in.");complete(session);close();}catch(error){setMessage(error instanceof Error?error.message:"Sign-in failed.");}}return <div className="overlay"><form className="sell-form" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><p className="eyebrow">NYX ACCOUNT</p><h2>{mode==="in"?"Welcome back":"Create account"}</h2><p className="muted">Username and password only for this prototype.</p><label>Username<input name="username" minLength={3} required/></label><label>Password<input name="password" type="password" minLength={6} required/></label>{message&&<p className="warning">{message}</p>}<button className="submit">{mode==="in"?"Sign in":"Create account"}</button><button type="button" className="example" onClick={()=>setMode(mode==="in"?"up":"in")}>{mode==="in"?"Need an account? Sign up":"Already have an account? Sign in"}</button></form></div>;}
createRoot(document.getElementById("root")!).render(<App/>);
