import type { Listing } from "./data";
const url = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;
const headers = (token?: string) => ({ apikey: key ?? "", Authorization: `Bearer ${token ?? key ?? ""}`, "Content-Type": "application/json" });
export type Session = { access_token: string; user: { id: string } };
export const getSession = (): Session | null => { try { return JSON.parse(localStorage.getItem("nyx-session") ?? "null"); } catch { return null; } };
const identity = (username: string) => `${username.trim().toLowerCase().replace(/[^a-z0-9_]/g, "")}@nyx.local`;
export async function signUp(username: string, password: string) { const r = await fetch(`${url}/auth/v1/signup`, { method:"POST", headers:headers(), body:JSON.stringify({email:identity(username),password}) }); const data = await r.json(); if (!r.ok) throw new Error(data.msg ?? data.message); const session = data.session as Session | null; if (session) { await fetch(`${url}/rest/v1/profiles`, {method:"POST",headers:{...headers(session.access_token),Prefer:"return=minimal"},body:JSON.stringify({id:session.user.id,username})}); localStorage.setItem("nyx-session",JSON.stringify(session)); } return session; }
export async function signIn(username: string, password: string) { const r = await fetch(`${url}/auth/v1/token?grant_type=password`, {method:"POST",headers:headers(),body:JSON.stringify({email:identity(username),password})}); const data = await r.json(); if (!r.ok) throw new Error(data.error_description ?? data.msg); localStorage.setItem("nyx-session",JSON.stringify(data)); return data as Session; }
export async function loadListings(): Promise<Listing[]> { if (!url || !key) return []; const r = await fetch(`${url}/rest/v1/listings?select=*&order=created_at.desc`,{headers:headers()}); if (!r.ok) return []; const rows = await r.json(); return rows.map((x: any) => ({...x, posted:new Date(x.created_at).toLocaleDateString()})); }
export async function saveListing(listing: Omit<Listing,"id"|"posted">, session: Session) { const r = await fetch(`${url}/rest/v1/listings`,{method:"POST",headers:{...headers(session.access_token),Prefer:"return=representation"},body:JSON.stringify(listing)}); if (!r.ok) throw new Error("Supabase could not save this listing. Run supabase-setup.sql first."); const [row] = await r.json(); return {...row,posted:"Just now"} as Listing; }
